name: HackMerced Build CI

on: 
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - bug/* # Push events to branches matching refs/heads/bug/*
      - feature/* # Push events to branches matching refs/heads/feature/*
      - develop # Push events to branches matching refs/heads/develop
      - master # Push events to branches matching refs/heads/master

    # Sequence of patterns matched against refs/tags
    tags:
      - v0.x # Push events to v0.x tags
      - v1.x # Push events to v1.x tags

jobs:
  build:
    name: Test application and make sure it runs on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [11.x]
        os: [ubuntu-latest]

    steps:
    - name: Checkout to current branch
      uses: actions/checkout@v2

    - name: Configure Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup 
      run: |
        echo 'Running Setup...'
        yarn setup

    - name: Test Server
      env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          MONGO_URI_TESTS: ${{ secrets.MONGO_URI_TESTS }}
          CI: true
      run: |
        echo 'Testing Server routes'
        yarn test

    - name: Build React
      run: |
        echo 'Building React Application...'
        cd client
        yarn build

